{{- if .Values.rbac.enable }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: skale-controller-manager-role
rules:
  - apiGroups: ["core.skale.io"]
    resources: ["skales"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

  - apiGroups: ["core.skale.io"]
    resources: ["skales/finalizers"]
    verbs: ["update"]

  - apiGroups: ["core.skale.io"]
    resources: ["skales/status"]
    verbs: ["get", "patch", "update"]

  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "update", "patch"]

  - apiGroups: ["skale.skale.io"]
    resources: ["skales", "skales/status"]
    verbs: ["get", "list", "watch", "update", "patch"]

  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
{{- end -}}
